// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeloraDX.Infrastructure.Data;

#nullable disable

namespace VeloraDX.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VeloraDX.Domain.Entities.BlogCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BlogCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Yapay Zeka",
                            Slug = "yapay-zeka"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Yazılım Geliştirme",
                            Slug = "yazilim-gelistirme"
                        },
                        new
                        {
                            Id = 3,
                            Name = "İçgörüler",
                            Slug = "icgorular"
                        });
                });

            modelBuilder.Entity("VeloraDX.Domain.Entities.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MetaTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Dr. Ahmet Kaya",
                            CategoryId = 1,
                            Content = "Generative AI, multimodal modeller, agentic AI ve daha birçok gelişme 2024 yılında bekleniyor...",
                            CoverImageUrl = "https://images.unsplash.com/photo-1555949519-bfb4dd1b9b41?w=800",
                            CreatedAt = new DateTime(2026, 7, 4, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            Excerpt = "2024 yılında AI endüstrisini şekillendirecek ana trendlere göz atalım.",
                            IsPublished = true,
                            MetaDescription = "2024 yılının en önemli AI trendlerini keşfedin. Generative AI, multimodal modeller ve daha fazlası.",
                            MetaTitle = "2024 Yapay Zeka Trendleri - VeloraDX",
                            PublishedAt = new DateTime(2026, 6, 14, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            Slug = "2024-yapay-zeka-trendleri",
                            Title = "2024 Yapay Zeka Trendleri"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Murat Çetin",
                            CategoryId = 2,
                            Content = "Mikro hizmetler, ölçeklenebilir ve esnek sistemler geliştirmenin anahtarıdır. Bu rehberde size step-by-step nasıl kuracağınızı gösterelim...",
                            CoverImageUrl = "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800",
                            CreatedAt = new DateTime(2026, 7, 4, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            Excerpt = "Modern yazılım geliştirmede mikro hizmetler mimarisinin avantajları ve zorlukları.",
                            IsPublished = true,
                            MetaDescription = "Yazılım geliştirmede mikro hizmetler mimarisinin tam rehberi. Avantajlar, zorluklar ve best practices.",
                            MetaTitle = "Mikro Hizmetler Mimarisi Rehberi",
                            PublishedAt = new DateTime(2026, 6, 19, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            Slug = "mikro-hizmetler-mimarisi-rehberi",
                            Title = "Mikro Hizmetler Mimarisi Rehberi"
                        });
                });

            modelBuilder.Entity("VeloraDX.Domain.Entities.CaseStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CaseStudies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientName = "TurboShop A.Ş.",
                            Content = "TurboShop, yıllık 50 milyon ziyaretçisi olan bir e-ticaret platformu. Ürün önerilemeleri algoritmasını geliştirerek, müşteri başına ortalama sepetin %35 arttığını gördük.",
                            CoverImageUrl = "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800",
                            CreatedAt = new DateTime(2026, 7, 4, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            Industry = "E-Ticaret",
                            IsActive = true,
                            PublishedAt = new DateTime(2026, 6, 4, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            Slug = "e-ticaret-ai-optimizasyonu",
                            Summary = "Büyük e-ticaret platformunun ürün önerilerini AI ile optimize ederek satışları %35 artırdık.",
                            Title = "E-Ticaret Platformu AI Optimizasyonu"
                        },
                        new
                        {
                            Id = 2,
                            ClientName = "Acibadem Sağlık Grubu",
                            Content = "Hastane idari işlemleri ve tıbbi kayıtları NLP ile otomasyonlaştırarak, kayıt girişi sürelerini önemli ölçüde kısalttık.",
                            CoverImageUrl = "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800",
                            CreatedAt = new DateTime(2026, 7, 4, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            Industry = "Sağlık",
                            IsActive = true,
                            PublishedAt = new DateTime(2026, 5, 20, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            Slug = "saglik-kurumu-nlp-cozumu",
                            Summary = "Hastane kayıtlarında NLP uygulamalarıyla, tanı doğruluğu %28 arttı, işlem süresi %40 kısaldı.",
                            Title = "Sağlık Kurumu NLP Çözümü"
                        });
                });

            modelBuilder.Entity("VeloraDX.Domain.Entities.CompanyStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CompanyStats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Label = "Tamamlanan Proje",
                            Value = "150+"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Label = "Memnun Müşteri",
                            Value = "50+"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Label = "Ekip Üyesi",
                            Value = "35+"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Label = "Yıl Tecrübe",
                            Value = "20+"
                        });
                });

            modelBuilder.Entity("VeloraDX.Domain.Entities.ContactSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ContactSubmissions");
                });

            modelBuilder.Entity("VeloraDX.Domain.Entities.JobOpening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("JobOpenings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 4, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            Department = "Araştırma & Geliştirme",
                            Description = "Transformatif AI çözümleri geliştirmek için deneyimli bir mühendis arıyoruz.",
                            EmploymentType = "Tam Zamanlı",
                            IsActive = true,
                            Location = "İstanbul",
                            PostedAt = new DateTime(2026, 6, 29, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            Requirements = "5+ yıl AI/ML deneyimi\nPython, TensorFlow, PyTorch\nDeep Learning bilgisi",
                            Slug = "senior-yapay-zeka-muhendisi",
                            Title = "Senior Yapay Zeka Mühendisi"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 4, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            Department = "Ürün Geliştirme",
                            Description = "Cloud-native web uygulamaları geliştirmek için yetenekli bir developer arıyoruz.",
                            EmploymentType = "Tam Zamanlı",
                            IsActive = true,
                            Location = "İstanbul",
                            PostedAt = new DateTime(2026, 7, 1, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            Requirements = "3+ yıl full-stack geliştirme\n.NET Core ve React bilgisi\nCloud services (Azure, AWS)",
                            Slug = "full-stack-web-developer",
                            Title = "Full Stack Web Developer"
                        });
                });

            modelBuilder.Entity("VeloraDX.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Özel eğitilmiş AI modelleri ile işlemlerinizi otomate edin, verimliliği artırın ve müşteri deneyimini iyileştirin.",
                            CreatedAt = new DateTime(2026, 7, 4, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            DisplayOrder = 1,
                            IconName = "Brain",
                            IsActive = true,
                            ShortDescription = "Mevcut sistemlerinize yapay zeka gücü ekleyin.",
                            Slug = "yapay-zeka-entegrasyonu",
                            Title = "Yapay Zeka Entegrasyonu"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Endüstri deneyimli danışmanlarımız, organizasyonunuzun AI yetkinliğini geliştirmesi için yol haritası çizer.",
                            CreatedAt = new DateTime(2026, 7, 4, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            DisplayOrder = 2,
                            IconName = "Compass",
                            IsActive = true,
                            ShortDescription = "Dijital dönüşüm yolculuğunuzda AI stratejisi belirleyin.",
                            Slug = "ai-donusum-danismanlik",
                            Title = "AI Dönüşüm Danışmanlığı"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Cloud-native, microservices ve modern architecture'ları kullanarak, yüksek performanslı ve bakımı kolay yazılımlar geliştiririz.",
                            CreatedAt = new DateTime(2026, 7, 4, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            DisplayOrder = 3,
                            IconName = "Code",
                            IsActive = true,
                            ShortDescription = "İş gereksinimlerinize uygun ölçeklenebilir yazılım çözümleri.",
                            Slug = "ozel-yazilim-gelistirme",
                            Title = "Özel Yazılım Geliştirme"
                        });
                });

            modelBuilder.Entity("VeloraDX.Domain.Entities.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "AI endüstrisinde 15+ yıl deneyim, Stanford ve MIT'den ders almış.",
                            CreatedAt = new DateTime(2026, 7, 4, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            DisplayOrder = 1,
                            Name = "Dr. Ayşe Aktaş",
                            PhotoUrl = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
                            Title = "Kurucu & Yapay Zeka Stratejisti"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Yazılım girişimciliğinde 20+ yıl, 5 startup kurmuş.",
                            CreatedAt = new DateTime(2026, 7, 4, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            DisplayOrder = 2,
                            Name = "Emre Yıldız",
                            PhotoUrl = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
                            Title = "Başkan Yönetici"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Ürün yönetiminde ve UX tasarımında uzman.",
                            CreatedAt = new DateTime(2026, 7, 4, 21, 20, 58, 662, DateTimeKind.Utc).AddTicks(9279),
                            DisplayOrder = 3,
                            Name = "Zeynep Kara",
                            PhotoUrl = "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400",
                            Title = "Ürün Direktörü"
                        });
                });

            modelBuilder.Entity("VeloraDX.Domain.Entities.BlogPost", b =>
                {
                    b.HasOne("VeloraDX.Domain.Entities.BlogCategory", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VeloraDX.Domain.Entities.BlogCategory", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
